/**
 * Statement of Works (SoW) document model — spec: sow-merge-mapping.md.
 *
 * A SoW is generated by merging an engagement's Blueprint (capability-map.json
 * + engagement-model.json) into the Polynize Statement of Works template. The
 * merge output persists per engagement as `sow/sow.json`.
 *
 * Two fill types live in this doc:
 *   - AUTO  — content derived from the Blueprint at generation time, stored as
 *             an editable snapshot in `auto`.
 *   - HUMAN — commercial / legal fields not in the Blueprint, stored in
 *             `human` as a value-or-null map. A null (or empty) value renders
 *             as a "NEEDS INPUT" badge for a team member to complete.
 *
 * STATIC content (the Service Agreement clauses 1-25, the SoW's fixed legal
 * prose) is NOT stored here — it is the same for every engagement and lives in
 * lib/sow/template.ts. Only the per-engagement merge output is persisted.
 *
 * "Strict on generate, liberal on read": this schema validates the file the
 * generator writes. The reader uses the lenient variant so an older or
 * hand-edited file still loads.
 */

import { z } from 'zod';

export const SOW_SCHEMA_VERSION = '1.0';

/** One row of the §3.1 Agent Team table. */
export const SowAgentSchema = z.object({
  name: z.string(),
  role: z.string(),
});
export type SowAgent = z.infer<typeof SowAgentSchema>;

/** One row of the §3.4 capability schedule. */
export const SowCapabilityRowSchema = z.object({
  id: z.string(),
  name: z.string(),
  /** "How it's done": Agent (automated) / Hybrid / Human (excluded). */
  how: z.string(),
  /** "Human check / handoff": completion_action, or a held/no-handoff note. */
  human_check: z.string(),
});
export type SowCapabilityRow = z.infer<typeof SowCapabilityRowSchema>;

/** One row of the §4 Targets table. */
export const SowTargetSchema = z.object({
  capability: z.string(),
  target: z.string(),
});
export type SowTarget = z.infer<typeof SowTargetSchema>;

/** One §5.1 motion. */
export const SowMotionSchema = z.object({
  label: z.string(),
  description: z.string(),
});
export type SowMotion = z.infer<typeof SowMotionSchema>;

/**
 * AUTO content — the Blueprint-derived snapshot. Editable in-Console; edits
 * overwrite these stored values (the Blueprint is not re-read on edit).
 */
export const SowAutoSchema = z.object({
  engagement_name: z.string(),
  /** §3 Background — from capability_map.interpretation. */
  background: z.string(),
  /** §3.1 — team.agents, team_leader row first. */
  agent_team: z.array(SowAgentSchema),
  /** §3.2 — scope_brief.scope_inclusions. */
  in_scope: z.array(z.string()),
  /** §3.3 — scope_brief.scope_exclusions + excluded_capabilities. */
  out_of_scope: z.array(z.string()),
  /** §3.4 — one row per capability. */
  capability_schedule: z.array(SowCapabilityRowSchema),
  /** §4 — engagement-model benchmarks restated (held / At-Benchmark skipped). */
  targets: z.array(SowTargetSchema),
  /** §5.1 — engagement-model.motions. */
  motions: z.array(SowMotionSchema),
  /** §5.2 — the 8 sprint stages (constant, stored for completeness). */
  build_sequence: z.array(z.string()),
  /** §2 summary — human-held / human-checked capability names. */
  human_held: z.array(z.string()),
  /** §6.1(b) — best-effort integrations list from work_shape inputs. */
  integrations: z.array(z.string()),
});
export type SowAuto = z.infer<typeof SowAutoSchema>;

/**
 * HUMAN fields — a value-or-null map keyed by the field keys defined in
 * lib/sow/template.ts (HUMAN_FIELDS). null or empty renders as NEEDS INPUT.
 */
export const SowHumanSchema = z.record(z.string(), z.string().nullable());
export type SowHuman = z.infer<typeof SowHumanSchema>;

export const SowDocSchema = z.object({
  schema_version: z.literal(SOW_SCHEMA_VERSION),
  generated_at: z.string(),
  /** "<slug> Blueprint v<x>". */
  generated_from: z.string(),
  /** System reference, e.g. SOW-roxburys-20260604. */
  sow_reference: z.string(),
  auto: SowAutoSchema,
  human: SowHumanSchema,
});
export type SowDoc = z.infer<typeof SowDocSchema>;

/**
 * Lenient read schema. Tolerates a missing/unknown schema_version and a
 * partial `auto` block (older generations), filling gaps at the call site.
 * Unknown human keys pass through. Used by the reader (sow-io); the generator
 * always writes the strict shape above.
 */
export const LenientSowDocSchema = z.object({
  schema_version: z.string().optional(),
  generated_at: z.string().optional(),
  generated_from: z.string().optional(),
  sow_reference: z.string().optional(),
  auto: z
    .object({
      engagement_name: z.string().optional(),
      background: z.string().optional(),
      agent_team: z.array(SowAgentSchema).optional(),
      in_scope: z.array(z.string()).optional(),
      out_of_scope: z.array(z.string()).optional(),
      capability_schedule: z.array(SowCapabilityRowSchema).optional(),
      targets: z.array(SowTargetSchema).optional(),
      motions: z.array(SowMotionSchema).optional(),
      build_sequence: z.array(z.string()).optional(),
      human_held: z.array(z.string()).optional(),
      integrations: z.array(z.string()).optional(),
    })
    .passthrough(),
  human: z.record(z.string(), z.string().nullable().optional()),
});
